# -*- coding: utf-8 -*-
"""factorial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_YC3PDy9G4keaiUl5lfzCw5KJTO4I0bc
"""

n = int(input("Enter a number: "))
fact = 1
for i in range(1,n+1):
  fact = fact*i
print(fact)

